# Adapted from https://www.hassen.io/posts/2024/06/ci-cd-for-rails-8-github-actions-kamal/
name: ci

on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write
  id-token: write


jobs:
  deploy:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'  # Fixed to match branch name
    runs-on: ubuntu-24.04
    env:
      RAILS_ENV: production
      BUNDLE_WITH: tools
      BUNDLE_WITHOUT: "development test"
      DOCKER_BUILDKIT: 1

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure 1Password Service Account
        uses: 1password/load-secrets-action/configure@v2
        with:
          service-account-token: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}

      - name: Load secrets from 1Password
        uses: 1password/load-secrets-action@v2
        with:
          export-env: true
        env:
          KAMAL_REGISTRY_PASSWORD: "op://Dev_Keys/Erudite_Prod/KAMAL_REGISTRY_PASSWORD"
          RAILS_MASTER_KEY: "op://Dev_Keys/Erudite_Prod/PROD_MASTER_KEY"
          SSH_PRIVATE_KEY: "op://Dev_Keys/ec2_aws/private key"

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Deploy using Kamal
        run: bin/kamal deploy
        env:
          SSH_PRIVATE_KEY: ${{ env.SSH_PRIVATE_KEY }}
          RAILS_MASTER_KEY: ${{ env.RAILS_MASTER_KEY }}
          KAMAL_REGISTRY_PASSWORD: ${{ env.KAMAL_REGISTRY_PASSWORD }}
